-- New Categories Migration for EightHand Furniture
-- This script removes old categories and inserts new ones without image_url

-- Delete all existing categories
DELETE FROM categories;

-- Insert new categories
INSERT INTO categories (name, description) VALUES
('Cabinet/Almira', 'Storage solutions for your home'),
('Dining Tables', 'Elegant dining tables with epoxy finishes'),
('Bedroom Set', 'Coordinated furniture for your bedroom'),
('Modular Work Station', 'Customizable office configurations'),
('Wooden Wash Basin', 'Unique bathroom solutions'),
('Cash Counter', 'Functional checkout stations for retail'),
('End Table', 'Functional and beautiful end tables'),
('Dinner Wagon', 'Mobile serving solutions for your dining needs'),
('Display Cabinet', 'Showcase your collectibles in these elegant cabinets'),
('Office Desk', 'Professional work spaces for your office'),
('Desks', 'Functional and stylish desks for your workspace'),
('Arm Chair', 'Comfortable arm chairs for relaxation'),
('Living Room Set', 'Complete furniture solutions for your living room'),
('Reception Furniture', 'Create a welcoming entrance for your business'),
('Shelving', 'Bookshelves and display units'),
('Office Set', 'Complete solutions for your office space'),
('Study Table', 'Productive work spaces for your home or office'),
('Kitchen Counter Top', 'Beautiful surfaces for your kitchen'),
('Lamp/Light/Chandelier', 'Illuminating options for your home'),
('Break Room Furniture', 'Comfortable spaces for employee relaxation'),
('Dining Table', 'Elegant dining tables for family gatherings'),
('Restaurant Set', 'Full furnishing options for dining establishments'),
('Epoxy Table', 'Beautiful custom epoxy tables for your home or office'),
('PU Flooring', 'Durable industrial flooring solutions'),
('Industrial Solutions', 'Durable furniture for industrial settings'),
('Bed Side Table', 'Convenient storage for beside your bed'),
('Bedroom', 'Bedroom furniture including nightstands and dressers'),
('Shoe Rack', 'Organized storage for your footwear'),
('Carpet/Rug', 'Beautiful floor coverings to complete your space'),
('Dressing Table', 'Beautiful dressing tables for your bedroom'),
('Shelf', 'Functional and stylish shelving options'),
('Dining Chair', 'Comfortable and stylish dining chairs'),
('Coffee Tables', 'Stylish coffee tables for your living room'),
('Project Execution', 'Full-service project management for your interior needs'),
('Bar Stool', 'Elevated seating for your bar or counter'),
('Dining Sets', 'Complete dining table and chair sets'),
('Bed', 'Comfortable sleeping solutions for your bedroom'),
('Store Cabinet', 'Storage solutions for commercial spaces'),
('Lab Clear Coat', 'Protective coatings for laboratory surfaces'),
('Book Shelf', 'Display and organize your book collection'),
('Epoxy Services', 'Custom epoxy applications for various surfaces'),
('Sofa/Couch/Bean', 'Comfortable seating options for your living area'),
('Center Table', 'Stylish center tables for your living room'),
('Interior Consultation', 'Professional design advice for your space'),
('Visitor Chair', 'Seating options for your office guests'),
('Fine Dining Furniture', 'Elegant furniture for restaurants'),
('Portable Partition', 'Flexible room dividers for versatile spaces'),
('Murphy Bed', 'Space-saving bed solutions'),
('Console Tables', 'Beautiful console tables for entryways'),
('TV Cabinet', 'Stylish storage for your entertainment system'),
('Conference Table', 'Meeting solutions for your business')
ON CONFLICT (name) DO NOTHING;
